"""SU2-NEMO config generation and batch execution helpers.

Generates run.cfg files for SU2-NEMO (two-temperature coupled-chemistry)
runs, suitable for the same per-case directory layout as run_cfd_batch.py
uses for SU2 Euler. The config template follows what was validated in
docs/SU2_NEMO_FIX.md.

Usage
-----
    from plasmanet.nemo_config import write_nemo_config, nemo_env
    write_nemo_config(
        path="case_dir/run.cfg",
        mach=10, altitude_km=30,
        gas_model="AIR-5",
        nose_radius_m=0.08,
    )
    # Then run SU2_CFD with the env from nemo_env():
    env = nemo_env(su2_nemo_prefix="/opt/su2-nemo")
    subprocess.run(["/opt/su2-nemo/bin/SU2_CFD", "run.cfg"], env=env)

The environment variables must be set for SU2_CFD to find:
  LD_LIBRARY_PATH=$su2_nemo_prefix/lib
  MPP_DATA_DIRECTORY=$su2_nemo_prefix/mpp-data
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

from .physics import standard_atmosphere


# Species order for each SU2-NEMO gas model (mass-fraction array index → species)
SPECIES_ORDER = {
    "AIR-5":  ["N2", "O2", "NO", "N", "O"],           # built-in SU2_NONEQ
    "AIR-7":  ["N2", "O2", "NO", "N", "O", "N2+", "e-"],  # built-in SU2_NONEQ
    "air_5":  ["N", "O", "NO", "N2", "O2"],           # Mutation++ mixture file
    "air_11": ["e-", "N+", "O+", "NO+", "N2+", "O2+", "N", "O", "NO", "N2", "O2"],
}

# Default freestream mass fractions by gas model (0.77 N2, 0.23 O2 ambient air)
DEFAULT_FREESTREAM = {
    "AIR-5":  "(0.77, 0.23, 0.0, 0.0, 0.0)",
    "AIR-7":  "(0.77, 0.23, 0.0, 0.0, 0.0, 0.0, 0.0)",
    "air_5":  "(0.0, 0.0, 0.0, 0.77, 0.23)",
    "air_11": "(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.77, 0.23)",
}


def _fluid_model_for(gas_model: str) -> str:
    """Return the FLUID_MODEL that pairs with a given GAS_MODEL."""
    if gas_model in ("AIR-5", "AIR-7", "ARGON", "N2"):
        return "SU2_NONEQ"
    if gas_model in ("air_5", "air_11", "air_11_legacy", "Mars_19"):
        return "MUTATIONPP"
    raise ValueError(f"Unknown gas_model {gas_model!r}")


def _time_scheme_for(gas_model: str) -> str:
    """EULER_IMPLICIT is supported by built-in SU2_NONEQ; MUTATIONPP only
    supports EULER_EXPLICIT in SU2 v7.5.1."""
    if _fluid_model_for(gas_model) == "MUTATIONPP":
        return "EULER_EXPLICIT"
    return "EULER_IMPLICIT"


def _cfl_for(gas_model: str) -> float:
    """Conservative CFL for stability. Implicit can handle larger values;
    explicit needs smaller."""
    if _fluid_model_for(gas_model) == "MUTATIONPP":
        return 0.3
    return 1.0


def _iters_for(gas_model: str) -> int:
    """MUTATIONPP+explicit needs many more iterations to converge."""
    if _fluid_model_for(gas_model) == "MUTATIONPP":
        return 20000
    return 2000


def write_nemo_config(
    path: str,
    mach: float,
    altitude_km: float,
    gas_model: str = "AIR-5",
    mesh_filename: str = "mesh.su2",
    convergence_min: float = -8.0,
    flux_scheme: str = "LAX-FRIEDRICH",  # more stable than AUSM for NEMO in our experience
    muscl: bool = True,
    iters: Optional[int] = None,
    cfl: Optional[float] = None,
    output_freq: int = 200,
    freestream_composition: Optional[str] = None,
    marker_euler: str = "( body )",
    marker_far: str = "( farfield )",
) -> None:
    """Write a SU2-NEMO config file at path.

    Config template validated in docs/SU2_NEMO_FIX.md. Assumes a mesh
    with `body` and `farfield` markers in SU2 format.
    """
    T_inf, p_inf, _, _ = standard_atmosphere(altitude_km)
    fluid_model = _fluid_model_for(gas_model)
    time_scheme = _time_scheme_for(gas_model)
    cfl_val = cfl if cfl is not None else _cfl_for(gas_model)
    n_iters = iters if iters is not None else _iters_for(gas_model)
    composition = freestream_composition or DEFAULT_FREESTREAM[gas_model]

    lines = [
        "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
        "% SU2-NEMO configuration — auto-generated by plasmanet.nemo_config",
        f"% Case: Mach {mach} @ {altitude_km} km altitude, {gas_model} gas model",
        "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
        "",
        "% ---- SOLVER DEFINITION ----",
        "SOLVER= NEMO_EULER",
        f"GAS_MODEL= {gas_model}",
        f"GAS_COMPOSITION= {composition}",
        "MATH_PROBLEM= DIRECT",
        "RESTART_SOL= NO",
        "",
        "% ---- FLUID MODEL (critical: SU2_NONEQ for AIR-*, MUTATIONPP for air_*) ----",
        f"FLUID_MODEL= {fluid_model}",
        "",
        "% ---- FREESTREAM ----",
        f"MACH_NUMBER= {mach}",
        "AOA= 0.0",
        "SIDESLIP_ANGLE= 0.0",
        f"FREESTREAM_PRESSURE= {p_inf:.4f}",
        f"FREESTREAM_TEMPERATURE= {T_inf:.4f}",
        f"FREESTREAM_TEMPERATURE_VE= {T_inf:.4f}    % thermal equilibrium upstream",
        "",
        "% ---- BOUNDARY CONDITIONS ----",
        f"MARKER_EULER= {marker_euler}",
        f"MARKER_FAR= {marker_far}",
        f"MARKER_PLOTTING= {marker_euler}",
        f"MARKER_MONITORING= {marker_euler}",
        "",
        "% ---- NUMERICS ----",
        "NUM_METHOD_GRAD= WEIGHTED_LEAST_SQUARES",
        f"CFL_NUMBER= {cfl_val}",
        f"ITER= {n_iters}",
        f"CONV_NUM_METHOD_FLOW= {flux_scheme}",
        f"MUSCL_FLOW= {'YES' if muscl else 'NO'}",
        "SLOPE_LIMITER_FLOW= VENKATAKRISHNAN",
        "VENKAT_LIMITER_COEFF= 0.05",
        f"TIME_DISCRE_FLOW= {time_scheme}",
        "",
        "% ---- LINEAR SOLVER ----",
        "LINEAR_SOLVER= BCGSTAB",
        "LINEAR_SOLVER_ERROR= 1E-6",
        "LINEAR_SOLVER_ITER= 5",
        "",
        "% ---- CONVERGENCE ----",
        f"CONV_RESIDUAL_MINVAL= {convergence_min}",
        "CONV_STARTITER= 10",
        "",
        "% ---- IO ----",
        f"MESH_FILENAME= {mesh_filename}",
        "MESH_FORMAT= SU2",
        "CONV_FILENAME= history",
        "VOLUME_FILENAME= flow",
        "SURFACE_FILENAME= surface_flow",
        f"OUTPUT_WRT_FREQ= {output_freq}",
        "OUTPUT_FILES= (RESTART, PARAVIEW)",
        "",
    ]
    Path(path).write_text("\n".join(lines))


def nemo_env(su2_nemo_prefix: str = "/opt/su2-nemo") -> dict:
    """Environment dict for running SU2-NEMO.

    Pass to subprocess.run(env=...). Merges with os.environ.
    """
    env = dict(os.environ)
    lib_dir = f"{su2_nemo_prefix}/lib"
    mpp_dir = f"{su2_nemo_prefix}/mpp-data"
    # Prepend su2-nemo lib to LD_LIBRARY_PATH
    old_ld = env.get("LD_LIBRARY_PATH", "")
    env["LD_LIBRARY_PATH"] = f"{lib_dir}:{old_ld}" if old_ld else lib_dir
    env["MPP_DATA_DIRECTORY"] = mpp_dir
    return env


def nemo_shell_prefix(su2_nemo_prefix: str = "/opt/su2-nemo") -> str:
    """Shell-quoted prefix suitable for prepending to an SU2 command."""
    return (
        f"LD_LIBRARY_PATH={su2_nemo_prefix}/lib:$LD_LIBRARY_PATH "
        f"MPP_DATA_DIRECTORY={su2_nemo_prefix}/mpp-data "
    )
