#!/bin/bash
# Parallel SU2-NEMO batch runner.
# Mirrors run_parallel.sh but points at the NEMO build and sets the
# env vars required by Mutation++. Use this to re-run the existing
# 40-case plasmanet_cfd batch under NEMO instead of Euler.
#
# Prereqs:
#   /opt/su2-nemo/bin/SU2_CFD                   — built with -Denable-mpp=true
#   /opt/su2-nemo/lib/libmutation__.so          — Mutation++ shared lib
#   /opt/su2-nemo/mpp-data/                     — Mutation++ data files (mixtures, mechanisms, thermo, transfer, transport)
#
# Before first use on a fresh VM:
#   cd /tmp && git clone --depth 1 https://github.com/mutationpp/Mutationpp.git mutationpp-src
#   sudo mkdir -p /opt/su2-nemo/mpp-data
#   sudo cp -r /tmp/mutationpp-src/data/* /opt/su2-nemo/mpp-data/
#   sudo chmod -R a+r /opt/su2-nemo/mpp-data/
#
# Each case directory must contain a run.cfg generated by
# plasmanet.nemo_config.write_nemo_config(). The Euler run.cfg's from
# the prior batch will NOT work — they lack FLUID_MODEL= SU2_NONEQ.

SU2=/opt/su2-nemo/bin/SU2_CFD
WORK=/home/yarden/plasmanet_cfd_nemo
LOG=/home/yarden/batch_progress_nemo.log
MAX_PARALLEL=4

export LD_LIBRARY_PATH=/opt/su2-nemo/lib:$LD_LIBRARY_PATH
export MPP_DATA_DIRECTORY=/opt/su2-nemo/mpp-data

# Sanity checks
if [ ! -x $SU2 ]; then
    echo "ERROR: SU2-NEMO binary not found at $SU2" >&2
    exit 1
fi
if [ ! -d $MPP_DATA_DIRECTORY/mixtures ]; then
    echo "ERROR: Mutation++ data missing at $MPP_DATA_DIRECTORY/mixtures" >&2
    echo "       Run the install block in the header of this file." >&2
    exit 1
fi

echo "NEMO parallel batch started: $(date), max $MAX_PARALLEL jobs" > $LOG
echo "  SU2=$SU2" >> $LOG
echo "  LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $LOG
echo "  MPP_DATA_DIRECTORY=$MPP_DATA_DIRECTORY" >> $LOG

run_case() {
    local dir=$1
    local name=$(basename $dir)
    local cfg=$dir/run.cfg
    [ ! -f $cfg ] && return
    [ -f $dir/su2.exitcode ] && return

    local geom=$(echo $name | sed 's/_M[0-9].*//')
    local mesh=${geom}_domain.su2
    [ ! -f $dir/$mesh ] && cp $WORK/$mesh $dir/$mesh 2>/dev/null
    [ ! -f $dir/$mesh ] && echo "SKIP $name (no mesh)" >> $LOG && return

    # Confirm NEMO config (FLUID_MODEL= SU2_NONEQ or MUTATIONPP must be set)
    if ! grep -q "^FLUID_MODEL=" $cfg; then
        echo "SKIP $name (not a NEMO config — FLUID_MODEL missing)" >> $LOG
        return
    fi

    echo "START $name $(date)" >> $LOG
    cd $dir
    rm -f su2.log su2.exitcode
    $SU2 run.cfg > su2.log 2>&1
    echo $? > su2.exitcode
    local ec=$(cat su2.exitcode)
    echo "DONE $name exit=$ec $(date)" >> $LOG
}

dirs=($WORK/*/)
total=${#dirs[@]}
i=0
while [ $i -lt $total ]; do
    pids=()
    for j in $(seq 0 $((MAX_PARALLEL-1))); do
        idx=$((i+j))
        [ $idx -ge $total ] && break
        run_case "${dirs[$idx]}" &
        pids+=($!)
    done
    for pid in ${pids[@]}; do
        wait $pid
    done
    i=$((i+MAX_PARALLEL))
    echo "Batch progress: $i/$total done $(date)" >> $LOG
done

echo "NEMO parallel batch finished: $(date)" >> $LOG
